sudo: false

language: node_js
node_js:
- node
cache: npm

install:
- npm install cl
- npm install mocha
-npm install chai


script:
- npm test

deploy:
provider: heroku
skip-cleanup: true
github-token: $GITHUB_TOKEN
on:
branch: master
